Fix for arm64 Windows builds (#54)
The arm64 Windows build is currently broken with the following error:

```
../../src/webrtc/src/third_party/libvpx/source/libvpx/vp8/common/dequantize.c(11,10): fatal error: 'vpx_config.h' file not found
#include "vpx_config.h"
         ^~~~~~~~~~~~~~
1 error generated.
```

This commit is based on https://groups.google.com/a/chromium.org/g/feature-media-reviews/c/tFt_fG2RkFw, which indicates that arm64 Windows was incorrectly identified as `arm64-highbd` instead of `arm64` (for which a config folder exists). This fixes the arm64 Windows build

This commit also fixes the `unresolved external symbol vpx_highbd_...` errors. The original logic in this line was `if (is_chromeos_ash || is_win || is_mac)`, but got changed to `if (cpu_arch_full == "arm64-highbd")` by the Signal team to support Mac Catalyst builds. This broke arm64 Windows since its CPU arch is "arm64" but uses arm64-highbd sources.